version: "3.7"
volumes:
  mongodata:

services:
  app:
    image: blog:v1
    command: sh -c "npm install && npm run start"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}" # phần này ta định nghĩa ở file .env nhé
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
        - redis
        - db
    networks:
      - db-network
      - redis-network

  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - db-network
  
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    networks:
      - redis-network

#Docker network
networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge